### ISSUE TITLE
Your Definitive Edition doesn't support speed mods.

### ISSUE THREAD

**Issue by Ao28th28** [XPMUser/XPMUser.github.io#12]
What went wrong:
Speed mod error bug
How can I replicate this:
Unknown
Console log output:
You already know

**Comment by Daboss7173** [comment]
Lol. I know exactly why this doesn't work. Few issues with your code.

A: You're not loading the mod scripts in the first place
B: You're not running the function to check for mods when the game boots

Those two will fix the game speed, but the walk speed won't work because you didn't change the walk speed setting configuration to account for the fact that the settings menu is completely different in this version. So you'll need to fix that as well.

**Comment by XPMUser** [comment]
Only pde2016 and pde2019 do so.
